# Generated by Django 3.2.9 on 2022-02-21 17:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_bankcard'),
    ]

    operations = [
        migrations.RenameField(
            model_name='bankcard',
            old_name='cc_pin',
            new_name='Security_PIN',
        ),
    ]
