# Generated by Django 3.2.9 on 2022-02-21 18:20

import creditcards.models
import django.core.validators
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_rename_cc_pin_bankcard_security_pin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='Security_PIN',
            field=creditcards.models.SecurityCodeField(max_length=4, validators=[django.core.validators.RegexValidator(regex='[0-9]{4}')], verbose_name='security PIN'),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='cc_code',
            field=creditcards.models.SecurityCodeField(max_length=4, validators=[django.core.validators.RegexValidator(regex='[0-9]{4}')], verbose_name='CVV/CVC'),
        ),
    ]
