# Generated by Django 3.2.9 on 2022-02-21 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0006_alter_userbankaccount_phone_number'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankcard',
            name='Security_PIN',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='cc_code',
            field=models.CharField(max_length=512),
        ),
        migrations.AlterField(
            model_name='bankcard',
            name='cc_number',
            field=models.CharField(max_length=512),
        ),
    ]
